apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: wallet-service-success-rate
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: {{ .Values.canary.analysis.interval }}
      successCondition: result[0] >= {{ .Values.canary.analysis.successThreshold }}
      failureLimit: {{ .Values.canary.analysis.failureLimit }}
      provider:
        prometheus:
          address: http://observability-kube-prometh-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(istio_requests_total{destination_service_name="{{ "{{" }}args.service-name{{ "}}" }}", response_code!~"5.."}[1m])) or vector(0)
            /
            sum(rate(istio_requests_total{destination_service_name="{{ "{{" }}args.service-name{{ "}}" }}"}[1m])) > 0