apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service-green
  template:
    metadata:
      labels:
        app: wallet-service-green
    spec:
      containers:
        - name: wallet-service
          image: wallet-service:v2
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: wallet-service-secrets
